version: '3.9'

services:
  app:
    build: .
    command: mvn spring-boot:run
    volumes:
      - .:/app
    env_file: .env
    environment:
      - WAIT_HOSTS=db
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.oktion-app.rule=Host(`app.oktion.danielblandes.com`)
      - traefik.http.routers.oktion-app.tls=true
      - traefik.http.routers.oktion-app.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    depends_on:
      - db
      - phpmyadmin
    restart: always
  
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 2G
      MAX_EXECUTION_TIME: 3600
    labels:
      - traefik.enable=true
      - traefik.http.routers.oktion-phpmyadmin.rule=Host(`phpmyadmin.oktion.danielblandes.com`)
      - traefik.http.routers.oktion-phpmyadmin.tls=true
      - traefik.http.routers.oktion-phpmyadmin.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db:

networks:
  traefik-proxy:
    external: true